{% set name = "dvc-objects" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 969bc19847b76604327631ce0ad0f287efa549d87bac028b5c2eb17a0d610984

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >={{ python_min }}
    - fsspec >=2024.2.0
    - funcy >=1.14

test:
  imports:
    - dvc_objects
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-objects
  summary: Library for generic objects used in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - pmrowla
    - shcheklein
    - skshetry
