{% set name = "dvc-objects" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e13add661ab7766cc26493102c7981b5164351f0ca4ee33d080d1651d4b5899

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - funcy >=1.14
    - shortuuid >=0.5.0
    - tqdm >=4.63.1,<5
    - typing_extensions >=3.7.4
    - fsspec >=2022.10.0
    - packaging >=19

test:
  imports:
    - dvc_objects
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-objects
  summary: Library for generic objects used in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - pmrowla
    - shcheklein
    - skshetry
