{% set name = "dvc-objects" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b008d972acbac797e6290c529627e74d257935d7870da20f7da091c74027014

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm >=6.3.1
  run:
    - python >=3.8
    - funcy >=1.14
    - fsspec >=2022.10.0

test:
  imports:
    - dvc_objects
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/iterative/dvc-objects
  summary: Library for generic objects used in DVC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - efiop
    - pmrowla
    - shcheklein
    - skshetry
